name: 'CMake build'

on:
  push:
    branches: [  main  ]
  pull_request:
    branches: [  main  ]
  workflow_dispatch:

env:
  CONAN_V2_MODE : 1
  # GitHub actions automatically zstd compresses caches
  CCACHE_NOCOMPRESS : true
  # 3GB; 10GB total for 4 compile jobs and conan data
  CCACHE_MAXSIZE : 3G
  SCCACHE_CACHE_SIZE : 3G

jobs:

  # ---------------------------------------------------------------------------
  Linux:
    name: Linux ${{ matrix.config.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
        image:    [ ubuntu-22.04 ]
        os:       [ linux ]
        config:
        - {
            compiler: "clang",
            preset:   "linux-clang-release",
            apt-pkg:  "clang-14"
          }
        - {
            compiler: "clang-libc++",
            preset:   "linux-clang-libc++-debug",
            apt-pkg:  "clang-14 libc++-14-dev libc++abi-14-dev"
          }
        - {
            compiler: "clang-13-libc++",
            preset:   "linux-clang-13-libc++-debug",
            apt-pkg:  "clang-13 libc++-13-dev libc++abi-13-dev"
          }
        - {
            compiler: "gcc",
            preset:   "linux-gcc-release",
            apt-pkg:  "g++-11"
          }

    steps:

    - name: Install basic dependencies (Ubuntu)
      # fail-safe check - only Ubuntu this days
      if: startsWith(matrix.image, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y cmake ninja-build ccache
        if [[ -n "${{ matrix.config.apt-pkg }}" ]]; then
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ${{ matrix.config.apt-pkg }};
        fi

    - name: Install conan package manager
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel conan

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Github's cache for conan
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}-${{ matrix.config.compiler }}-conan-${{ hashFiles('conanfile.txt') }}
        path: |
          ~/.conan

    - name: Setup Github's cache for compiler cache
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}-${{ matrix.config.compiler }}-ccache
        path: |
          ~/.config/ccache
          ~/.cache/ccache

    - name: Configuration and build
      run: |
        cmake --preset ${{ matrix.config.preset }}
        cmake --build --preset ${{ matrix.config.preset }} -v

    - name: CCache statistics
      run: |
        ccache --show-stats

    - name: Run Unit Test
      run: |
        ctest --preset ${{ matrix.config.preset }}

    - name: Clean up conan's build & sources
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src

  # ---------------------------------------------------------------------------
  Windows:
    name: Windows ${{ matrix.config.compiler }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
        image:    [ windows-2022 ]
        os:       [ windows ]
        config:
        - {
            compiler: "msvc",
            preset:   "windows-msvc-release",
            vcvars:   "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat",
          }
# disabled, issues with conan to build boost          
#        - {
#            compiler: "clang",
#            preset:   "windows-msvc-clang-release",
#            vcvars:   "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat",
#          }

    steps:

    - name: Install basic dependencies
      run: |
        choco install ninja cmake sccache

    - name: Install conan package manager
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install wheel conan

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Github's cache for conan
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}-${{ matrix.config.compiler }}-conan-${{ hashFiles('conanfile.txt') }}
        path: |
          C:\\Users\\runneradmin\\.conan
          C:\\.conan

    - name: Setup Github's cache for compiler cache
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}-${{ matrix.config.compiler }}-sccache
        path: |
          C:\\Users\\runneradmin\\AppData\\Local\\Mozilla\\sccache

    - name: Configuration and build on Windows
      shell: cmd
      run: |
        call "${{ matrix.config.vcvars }}"
        cmake --preset ${{ matrix.config.preset }}
        cmake --build --preset ${{ matrix.config.preset }} -v

    - name: SCCache statistics
      run: |
        sccache --show-stats && sccache --stop-server

    - name: Run Unit Test
      run: |
        ctest --preset ${{ matrix.config.preset }}

    - name: Clean up conan's build & sources
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src

  # ---------------------------------------------------------------------------
  macOS:
    name: macOS ${{ matrix.config.compiler }}
    runs-on: ${{ matrix.image }}
    #if: false # always skip job
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
        image:    [ macos-12 ]
        os:       [ macos ]
        config:
        - {
            compiler: "clang",
            preset:   "macos-clang-debug",
          }

    steps:

    - name: Install basic dependencies
      run: |
        brew update
        brew install cmake ninja sccache
        # [LLVM will be updated to version 14 on July, 11 #5835](
        #  https://github.com/actions/runner-images/issues/5835)
        # set the path to homebrew's LLVM
        #echo "/opt/homebrew/opt/llvm@14/bin" >> $GITHUB_PATH

    - name: Install conan package manager
      run: |
        python3 -m pip install --upgrade pip
        pip3 --disable-pip-version-check --no-cache-dir install wheel conan

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Github's cache for conan
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}-${{ matrix.config.compiler }}-conan-${{ hashFiles('conanfile.txt') }}
        path: |
          ~/.conan

    - name: Setup Github's cache for compiler cache
      uses: actions/cache@v3
      with:
        key: ${{ matrix.os }}-${{ matrix.config.compiler }}-sccache
        path: |
          ~/Library/Caches/Mozilla.sccache

    - name: Configuration and build
      run: |
        #cmake -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@14)/bin/clang++ --preset ${{ matrix.config.preset }}
        cmake --preset ${{ matrix.config.preset }}
        cmake --build --preset ${{ matrix.config.preset }} -v

    - name: SCCache statistics
      run: |
        sccache --show-stats && sccache --stop-server

    - name: Run Unit Test
      run: |
        ctest --preset ${{ matrix.config.preset }}

    - name: Clean up conan's build & sources
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src
